# GET /services/data/v57.0/query?q=SELECT+Id,Name,LastName,ID_vod__c,Veeva_NWK_ID__c,Gender_vod__c,PersonEmail,National_ID_NWK__c,SIL_COD_AUDIT__c+FROM+Account HTTP/1.1
# Host: silaneslatam--full.sandbox.my.salesforce.com
# Authorization: Bearer 00D54000000YqUS!ARUAQJIoL9rLVWG43wAUBbBoON_Z9f1YxxVaVWYr3IV.bhaVXeC0bCPoEc8d68hk9U7y0ou1Q1S_PeXp6Qp1h2nC_YJ.ZsfR
# Cookie: BrowserId=mR9W5M6KEe2tDP9OoULkOw; CookieConsentPolicy=0:1; LSKey-c$CookieConsentPolicy=0:1

GET /services/data/v57.0/query?q=SELECT+FIELDS(ALL)+FROM+Account+LIMIT+100 HTTP/1.1
Host: silaneslatam--full.sandbox.my.salesforce.com
Authorization: Bearer 00D54000000YqUS!ARUAQG6_ntzW5Nb.R5lwJMoxrxALviJP3E_jxQNl_CedLDCRNs0WhMWDz.Pv07JT4HYU5rcI5h5PkVo_fQLKoVvoQfOCUXrH
Cookie: BrowserId=mR9W5M6KEe2tDP9OoULkOw; CookieConsentPolicy=0:1; LSKey-c$CookieConsentPolicy=0:1